### ISSUE TITLE
Support boolean like search?

### ISSUE THREAD

**Issue by xaljer** [variar/klogg#320]
reference to https://github.com/Genivia/ugrep, this tool support many search options including boolean search.

(By the way, may be some research can be done to see if klogg can integrate this tool as a search engine to introduce more powerful feature like fuzzy search.)

Currently, klogg's invert search is global, but I think boolean like search which can implement "search this but not that" is more powerful and useful.
This also can be done by native regexp with complex grammar, but I think GUI can do more to simplify this. Such as there are two window to input regexp, one for pick pattern, another for invert pattern.

**Comment by variar** [comment]
I'll take a look at this ugrep tool. 

#22 and #5 mentions the idea of having several inputs for include/exclude regex. Internally klogg already has support for multiple patterns in the form of `(pattern1 OR pattern 2) AND NOT (pattern3 OR pattern4)`. But there is no GUI for this yet.

**Comment by variar** [comment]
I've implemented this feature in builds 21.05.0.994+. There is new button in search panel that toggle boolean combination mode. In this mode all patterns must be enclosed in `"`.  Following operators are supported:

- `and`, `&` -- whole pattern will match at some line if both sub-patterns of this operator match at that line
-  `or` , `|` -- whole pattern will match at some line if either one of sub-patterns of this operator match at that line
- `not` -- inverses sub-pattern.  Sub-pattern must be enclosed in `()` 

Example or valid pattern combination:
```
("pattern 1" or "pattern 2") and not("pattern 3" and "pattern 4")
```

Unfortunately, I haven't found fast implementation of boolean expression evaluator yet. So boolean combination mode is noticeably slower than usual regular expressions search.

**Comment by variar** [comment]
Here is a simple demo:

https://user-images.githubusercontent.com/1620716/119331693-54dcc880-bc90-11eb-8e43-f22f8c36aff7.mp4

**Comment by variar** [comment]
I've checked ugrep internals. It is using RE-flex library for regex search. I've managed to integrate it into klogg, however, hyperscan engine is faster in my tests.

It might be possible to integrate fuzzy matcher from RE-flex. Some performance loss in that case is expected.

**Comment by xaljer** [comment]
I've tested this feature, and it does helps my work, thank you!
But I think it still not so convenient to write the pattern in this mode and can not co-work with "add to search".  Just imagine some optimization idea:
- one include regex window and one exclude regex window, exclude window is only opened if the mode is on.
- provide "add to include search" and "add to exclude search" .

**Comment by variar** [comment]
I've made add to search/exclude from search usable in boolean combination mode.

I'm thinking of adding additional panel of "advanced" search controls. That panel will contain things like match context(include some lines before/after match). Additional "exclude filter" can go there. However, this will be a third way to exclude something from search. Might be too much.

**Comment by variar** [comment]
I've moved idea with separate include and exclude regex window to separate issue. It is easier for me to track progress that way.
